name: api-bicis-app
region: fra1
services:
  - name: api-bicis
    environment_slug: php
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    github:
      branch: main
      deploy_on_push: true
      repo: jmrgjuan/api-bicis
